#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the strangeCounter function below.
def strangeCounter(t):
    c=1
    b=a=3
    while(c!=t):
        if(a==1):
            a=b*2
            b=a
            c=c+1
        else:
            a=a-1
            c=c+1
    return a

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    result = strangeCounter(t)

    fptr.write(str(result) + '\n')

    fptr.close()
