#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the weightedUniformStrings function below.
def weightedUniformStrings(s, queries):
    
    a = set()
    n = -1
    l = 0
    for c in s:
        b = ord(c) - ord('a') + 1
        a.add(b)
        if n == c:
            l += 1
            a.add(l*b)
        else:
            n = c
            l = 1
     
    val = []
    for q in queries:
        if q in a:
            val.append("Yes")
        else:
            val.append("No")
    return val

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    queries_count = int(input())

    queries = []

    for _ in range(queries_count):
        queries_item = int(input())
        queries.append(queries_item)

    result = weightedUniformStrings(s, queries)

    fptr.write('\n'.join(result))
    fptr.write('\n')

    fptr.close()
